on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --prod
        working-directory: .       

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cpcgrfrontend'
        slot-name: 'fedpmnt'
        publish-profile: $
        package: .
